=encoding utf-8

=head1 NAME

truncate-presentation - Presentation about Unicode::Truncate

=head1 LIVE

https://www.youtube.com/watch?v=123esmJWJTE&t=33m40s

(resumes after technical difficulties)

https://www.youtube.com/watch?v=123esmJWJTE&t=1h3m00s

=head1 VIEW

http://hoytech.github.io/truncate-presentation

=head1 SOURCE

https://github.com/hoytech/truncate-presentation/tree/gh-pages
